# EXAMPLE TERRAFORM VARIABLES FILE
# Copy this file to variable.tf and update with your actual AWS credentials

variable "access_key" {
  description = "AWS Access Key ID"
  type        = string
  default     = "YOUR_AWS_ACCESS_KEY_ID"
}

variable "secret_key" {
  description = "AWS Secret Access Key"
  type        = string
  default     = "YOUR_AWS_SECRET_ACCESS_KEY"
}

variable "region" {
  description = "AWS Region"
  type        = string
  default     = "ap-south-1"
}

variable "ami" {
  description = "Amazon Linux 2 AMI ID for your region"
  type        = string
  default     = "ami-0f918f7e67a3323f0"  # Amazon Linux 2 in ap-south-1
}

variable "subnet_id" {
  description = "Subnet ID where EC2 will be launched"
  type        = string
  default     = "subnet-xxxxxxxxxxxxxxxxx"  # Replace with your subnet ID
}

variable "key_name" {
  description = "EC2 Key Pair name for SSH access"
  type        = string
  default     = "your-key-pair-name"  # Replace with your key pair name
}

variable "instance_name" {
  description = "Name tag for the EC2 instance"
  type        = string
  default     = "CI-CD-Jenkins-Server"
}

variable "vpc_id" {
  description = "VPC ID where resources will be created"
  type        = string
  default     = "vpc-xxxxxxxxxxxxxxxxx"  # Replace with your VPC ID
}

# INSTRUCTIONS:
# 1. Copy this file: cp variable_example.tf variable.tf
# 2. Update variable.tf with your actual AWS credentials and infrastructure IDs
# 3. Never commit variable.tf to git (it's in .gitignore)
# 4. Note: .tfstate, .tfvars, and plan files are auto-generated by terraform - do not edit manually